//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Simple_Crypto
{
    using System;
    using System.Collections.Generic;
    
    public partial class InputLog
    {
        public int id { get; set; }
        public string message { get; set; }
        public System.DateTime time { get; set; }
    }
}
